-- AlterEnum
ALTER TYPE "SkinScanAngle" ADD VALUE IF NOT EXISTS 'FOREHEAD';
ALTER TYPE "SkinScanAngle" ADD VALUE IF NOT EXISTS 'LEFT_CHEEK';
ALTER TYPE "SkinScanAngle" ADD VALUE IF NOT EXISTS 'RIGHT_CHEEK';
ALTER TYPE "SkinScanAngle" ADD VALUE IF NOT EXISTS 'CHIN';
ALTER TYPE "SkinScanAngle" ADD VALUE IF NOT EXISTS 'NECK';
