import { Router } from 'express';
import { academyAuthenticate, academyRequireAdmin } from '../../../middleware/academy-auth.middleware';
import * as controller from './marketing.controller';
import { upload } from '../../../config/multer';
const router = Router();
router.get('/public/storefront', controller.storefront);
router.post('/public/banners/:id/event', controller.bannerEvent);
router.post('/public/leads', controller.lead);
router.post('/public/leads/unsubscribe/:token', controller.unsubscribe);
router.get('/public/email/open/:token', controller.emailOpen);
router.get('/public/email/click/:token', controller.emailClick);
router.post('/marketing/preview-code', academyAuthenticate, controller.previewCode);
router.get('/admin/marketing', academyAuthenticate, academyRequireAdmin, controller.adminList);
router.post('/admin/marketing/send-campaign', academyAuthenticate, academyRequireAdmin, controller.sendCampaign);
router.get('/admin/marketing/campaigns', academyAuthenticate, academyRequireAdmin, controller.campaigns);
router.post('/admin/marketing/test-campaign', academyAuthenticate, academyRequireAdmin, controller.testCampaign);
router.get('/admin/marketing/media', academyAuthenticate, academyRequireAdmin, controller.listMedia);
router.post('/admin/marketing/media', academyAuthenticate, academyRequireAdmin, upload.single('image'), controller.uploadMedia);
router.patch('/admin/marketing/leads/:id',academyAuthenticate,academyRequireAdmin,controller.updateLead);
router.delete('/admin/marketing/leads/:id',academyAuthenticate,academyRequireAdmin,controller.deleteLead);
router.post('/admin/marketing/banners', academyAuthenticate, academyRequireAdmin, controller.createBanner);
router.patch('/admin/marketing/banners/:id', academyAuthenticate, academyRequireAdmin, controller.updateBanner);
router.delete('/admin/marketing/banners/:id', academyAuthenticate, academyRequireAdmin, controller.deleteBanner);
router.post('/admin/marketing/promotions', academyAuthenticate, academyRequireAdmin, controller.createPromotion);
router.patch('/admin/marketing/promotions/:id', academyAuthenticate, academyRequireAdmin, controller.updatePromotion);
router.delete('/admin/marketing/promotions/:id', academyAuthenticate, academyRequireAdmin, controller.deletePromotion);
router.post('/admin/marketing/codes', academyAuthenticate, academyRequireAdmin, controller.createCode);
router.patch('/admin/marketing/codes/:id', academyAuthenticate, academyRequireAdmin, controller.updateCode);
router.delete('/admin/marketing/codes/:id', academyAuthenticate, academyRequireAdmin, controller.deleteCode);
export default router;
