import { NextFunction, Request, Response } from 'express';
import * as service from './marketing.service';
import * as media from './academy-media.service';
import { env } from '../../../config/env';
const run = (fn: (req: Request) => unknown, status = 200) => async (req: Request, res: Response, next: NextFunction) => { try { res.status(status).json({ data: await fn(req) }); } catch (error) { next(error); } };
export const storefront = run(() => service.publicStorefront());
export const bannerEvent = run(req => service.recordBannerEvent(req.params.id, req.body.type === 'click' ? 'click' : 'impression'), 204);
export const lead = run(req => service.saveLead(req.body), 201);
export const unsubscribe = run(req => service.unsubscribeLead(req.params.token));
export const adminList = run(() => service.listAdmin());
export const sendCampaign = run(req => service.sendMarketingCampaign(req.body), 202);
export const campaigns = run(()=>service.listCampaigns());
export const testCampaign = run(req=>service.sendCampaignTestForUser(req.body,req.academyUser!.id));
export const emailOpen=async(req:Request,res:Response)=>{await service.trackEmailOpen(req.params.token);res.set('Cache-Control','no-store').type('gif').send(Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64'));};
export const emailClick=async(req:Request,res:Response)=>{await service.trackEmailClick(req.params.token);const base=env.ACADEMY_URL??'http://localhost:5174';try{const target=new URL(String(req.query.url||'/'),base);res.redirect(target.origin===new URL(base).origin?target.toString():'/');}catch{res.redirect('/');}};
export const uploadMedia = run(req => media.uploadAcademyMedia(req.file,req.body),201);
export const listMedia = run(() => media.listAcademyMedia());
export const updateLead=run(req=>service.updateLead(req.params.id,req.body));
export const deleteLead=run(req=>service.deleteLead(req.params.id));
export const createBanner = run(req => service.createBanner(req.body), 201);
export const updateBanner = run(req => service.updateBanner(req.params.id, req.body));
export const deleteBanner = run(req => service.deleteBanner(req.params.id));
export const createPromotion = run(req => service.createPromotion(req.body), 201);
export const updatePromotion = run(req => service.updatePromotion(req.params.id, req.body));
export const deletePromotion = run(req => service.deletePromotion(req.params.id));
export const createCode = run(req => service.createCode(req.body), 201);
export const updateCode = run(req => service.updateCode(req.params.id, req.body));
export const deleteCode = run(req => service.deleteCode(req.params.id));
export const previewCode = run(req => service.previewDiscountCode(req.academyUser!.id, req.body));
