import { FormEvent, useEffect, useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { academyApi } from '@/api/academy.api';
import { MessageCircleHeart, Send, ShieldCheck } from 'lucide-react';

export function AcademyConsultation() {
  const client = useQueryClient(); const [content, setContent] = useState(''); const [sending, setSending] = useState(false); const end = useRef<HTMLDivElement>(null);
  const { data: room, isLoading } = useQuery({ queryKey: ['academy-chat'], queryFn: academyApi.getMyChatRoom, refetchInterval: 15000 });
  useEffect(() => end.current?.scrollIntoView({ behavior: 'smooth' }), [room?.messages?.length]);
  const send = async (event: FormEvent) => { event.preventDefault(); if(!content.trim() || !room?.id) return; setSending(true); try { await academyApi.sendChatMessage(content.trim(), room.id); setContent(''); await client.invalidateQueries({queryKey:['academy-chat']}); } finally { setSending(false); } };
  return <div className="consultation-page"><section className="consultation-hero"><div className="consultation-icon"><MessageCircleHeart /></div><p className="academy-kicker">Wsparcie w Akademii</p><h1>Zapytaj kosmetologa</h1><p>Potrzebujesz doprecyzowania materiału, informacji o technice lub wskazówki do ćwiczenia? Napisz — rozmowa jest prywatna.</p></section><section className="consultation-chat"><header><div><strong>Twoja konsultacja</strong><small>Odpowiedź pojawi się w tym wątku</small></div><ShieldCheck /></header><div className="consultation-messages">{isLoading ? <p>Ładujemy rozmowę…</p> : room?.messages?.length ? room.messages.map((message: any) => <div key={message.id} className={`consultation-message ${message.senderId === room.userId ? 'own' : ''}`}><p>{message.content}</p><small>{new Date(message.createdAt).toLocaleString('pl-PL', { day:'numeric', month:'short', hour:'2-digit', minute:'2-digit' })}</small></div>) : <div className="consultation-empty"><MessageCircleHeart /><strong>Rozpocznij rozmowę</strong><p>Opisz, przy którym materiale potrzebujesz wsparcia.</p></div>}<div ref={end} /></div><form onSubmit={send}><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Np. Jak rozpoznać przeciwwskazanie opisane w lekcji 2?" rows={2}/><button disabled={sending || !content.trim()}><Send />{sending ? 'Wysyłanie…' : 'Wyślij pytanie'}</button></form></section></div>;
}
