import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { academyApi } from '@/api/academy.api';

const statusLabel: Record<string,string> = { PENDING:'Oczekuje', PAID:'Opłacone', FAILED:'Nieudane', CANCELLED:'Anulowane', REFUNDED:'Zwrócone' };
export function AcademyOrdersAdmin() {
  const client = useQueryClient(); const [status,setStatus] = useState('ALL'); const [search,setSearch] = useState('');
  const { data: orders = [], isLoading } = useQuery({ queryKey:['academy','admin','orders',status,search], queryFn:()=>academyApi.adminGetOrders(status,search) });
  const refund = useMutation({ mutationFn: ({id,amount,reason}:{id:string;amount?:number;reason?:string})=>academyApi.adminRefundOrder(id,{amount,reason}), onSuccess:()=>{toast.success('Zwrot został zlecony');client.invalidateQueries({queryKey:['academy','admin','orders']});}, onError:(error:any)=>toast.error(error?.response?.data?.message||'Nie udało się zlecić zwrotu') });
  const askRefund = (order:any) => { const amountText = window.prompt(`Kwota zwrotu (puste = pełny zwrot, maks. ${Number(order.amount).toFixed(2)}):`, ''); if (amountText === null) return; const amount = amountText.trim() ? Number(amountText.replace(',','.')) : undefined; const reason = window.prompt('Powód zwrotu:', 'Zwrot na prośbę klienta') || ''; if (amount !== undefined && !Number.isFinite(amount)) return toast.error('Nieprawidłowa kwota'); refund.mutate({id:order.id,amount,reason}); };
  return <div className="academy-orders-admin"><header><p className="academy-kicker">Obsługa sprzedaży</p><h1>Zamówienia i zwroty</h1><p>Historia płatności, zdarzeń i dostępu do kursów.</p></header><div className="academy-order-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Szukaj po e-mailu, nazwie lub numerze" /><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Wszystkie statusy</option>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{isLoading?<p>Ładowanie…</p>:<div className="academy-order-table"><div className="head"><span>Zamówienie</span><span>Klient</span><span>Produkt</span><span>Kwota</span><span>Status</span><span>Akcje</span></div>{(orders as any[]).map(order=><details key={order.id}><summary><span><strong>{order.id}</strong><small>{new Date(order.createdAt).toLocaleString('pl-PL')}</small></span><span><strong>{order.user.name}</strong><small>{order.user.email}</small></span><span>{order.course?.title||order.bundle?.title}</span><span>{Number(order.amount).toFixed(2)} {order.currency}</span><span className={`status ${order.status.toLowerCase()}`}>{statusLabel[order.status]||order.status}</span><span>{order.status==='PAID'&&<button onClick={e=>{e.preventDefault();askRefund(order);}} disabled={refund.isPending}>Zwróć</button>}</span></summary><section><dl><div><dt>Faktura</dt><dd>{order.invoiceRequested ? order.invoiceNumber || 'oczekuje na numer' : 'nie żądano'}</dd></div><div><dt>Rozliczenie</dt><dd>{order.billingName}{order.billingTaxId ? ` · NIP ${order.billingTaxId}` : ''}</dd></div><div><dt>Zwrot</dt><dd>{order.refundAmount ? `${Number(order.refundAmount).toFixed(2)} ${order.currency}` : '—'}</dd></div></dl><h3>Zdarzenia</h3><ul>{order.events.map((event:any)=><li key={event.id}>{new Date(event.createdAt).toLocaleString('pl-PL')} · {event.type}</li>)}</ul></section></details>)}</div>}</div>;
}
