import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { academyApi } from '@/api/academy.api';
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, BookOpen, CircleDollarSign, Download, Eye, Filter, Search, ShoppingCart, TrendingUp, UserRound, UsersRound, X } from 'lucide-react';

const n=(value:number)=>new Intl.NumberFormat('pl-PL').format(value||0);
const money=(value:number)=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:0}).format(value||0);
const pct=(value:number)=>`${(value||0).toFixed(1).replace('.',',')}%`;
const date=(value:string)=>new Intl.DateTimeFormat('pl-PL',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value));

export function AcademyAnalytics(){
  const client=useQueryClient(); const [days,setDays]=useState(30); const [tab,setTab]=useState<'overview'|'customers'>('overview'); const [search,setSearch]=useState(''); const [customerFilter,setCustomerFilter]=useState('ALL');
  const dashboard=useQuery({queryKey:['admin','academy-analytics',days],queryFn:()=>academyApi.adminAnalyticsDashboard(days)});
  const customers=useQuery({queryKey:['admin','academy-customers'],queryFn:()=>academyApi.adminAnalyticsCustomers(),enabled:tab==='customers'});
  const courses=useQuery({queryKey:['admin','academy-courses-options'],queryFn:academyApi.adminGetCourses,enabled:tab==='customers'});
  const access=useMutation({mutationFn:({action,userId,courseId}:{action:'grant'|'revoke';userId:string;courseId:string})=>action==='grant'?academyApi.adminGrantCustomerCourse(userId,courseId):academyApi.adminRevokeCustomerCourse(userId,courseId),onSuccess:()=>client.invalidateQueries({queryKey:['admin','academy-customers']})});
  const filtered=useMemo(()=>((customers.data||[]) as any[]).filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(search.toLowerCase())).filter(c=>customerFilter==='BUYERS'?c.courses.length:customerFilter==='LEADS'?c.interestedCourses.length&&!c.courses.length:customerFilter==='EMPTY'?!c.courses.length&&!c.interestedCourses.length:true),[customers.data,search,customerFilter]);
  const data=dashboard.data; const s=data?.summary;
  return <div className="analytics-page">
    <header className="analytics-head"><div><p className="academy-kicker text-caramel">Centrum dowodzenia</p><h1>Sprzedaż i klienci</h1><p>Pełny obraz drogi od pierwszej wizyty do ukończenia kursu.</p></div><div className="analytics-period"><Filter />{[7,30,90,365].map(value=><button key={value} className={days===value?'active':''} onClick={()=>setDays(value)}>{value===365?'Rok':`${value} dni`}</button>)}</div></header>
    <nav className="analytics-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><BarChart3 />Przegląd</button><button className={tab==='customers'?'active':''} onClick={()=>setTab('customers')}><UsersRound />Baza klientów</button></nav>
    {tab==='overview'?(dashboard.isLoading?<Loading/>:<>
      <section className="analytics-kpis">
        <Kpi icon={<Eye/>} label="Odwiedzający sklep" value={n(s?.visitors)} note={`${n(s?.sessions)} sesji`} trend={s?.visitorChange}/>
        <Kpi icon={<UserRound/>} label="Wszystkie konta" value={n(s?.totalAccounts)} note={`+${n(s?.newAccounts)} w okresie`}/>
        <Kpi icon={<BookOpen/>} label="Oglądający kursy" value={n(s?.courseViewers)} note={`${pct(s?.visitorToCourseRate)} odwiedzających`} trend={s?.interestChange}/>
        <Kpi icon={<ShoppingCart/>} label="Rozpoczęte zakupy" value={n(s?.checkoutVisitors)} note={`${pct(s?.courseToCheckoutRate)} zainteresowanych`}/>
        <Kpi icon={<TrendingUp/>} label="Konwersja sprzedaży" value={pct(s?.conversionRate)} note={`${n(s?.sales)} dostępów w okresie`}/>
        <Kpi icon={<CircleDollarSign/>} label="Przychód online" value={money(s?.revenue)} note="Z opłaconych zamówień Stripe"/>
      </section>
      <section className="analytics-grid-main">
        <article className="analytics-card analytics-chart"><div className="analytics-card-title"><div><strong>Ruch w Akademii</strong><span>Unikalni użytkownicy dzień po dniu</span></div><Activity/></div><TrafficChart rows={data?.daily||[]}/></article>
        <article className="analytics-card"><div className="analytics-card-title"><div><strong>Lejek sprzedażowy</strong><span>Gdzie klienci odpadają</span></div><TrendingUp/></div><div className="analytics-funnel">{(data?.funnel||[]).map((item:any,index:number)=>{const base=data.funnel[0]?.value||1;return <div key={item.label}><div><span>{index+1}</span><strong>{item.label}</strong><b>{n(item.value)}</b></div><div className="analytics-funnel-bar"><i style={{width:`${Math.max(item.value/base*100,item.value?8:0)}%`}}/></div>{index>0&&<small>{pct(item.value/base*100)} ruchu początkowego</small>}</div>})}</div></article>
      </section>
      <section className="analytics-grid-bottom">
        <article className="analytics-card"><div className="analytics-card-title"><div><strong>Wyniki kursów</strong><span>Zainteresowanie i sprzedaż</span></div><BookOpen/></div><div className="analytics-course-table"><div className="analytics-table-head"><span>Kurs</span><span>Wyświetlenia</span><span>Zakup</span><span>Sprzedaż</span><span>Konwersja</span></div>{(data?.courses||[]).map((course:any)=><div key={course.id}><strong>{course.title}</strong><span>{n(course.uniqueViewers)}</span><span>{n(course.checkoutStarted)}</span><span>{n(course.sales)}</span><b>{pct(course.conversion)}</b></div>)}</div></article>
        <article className="analytics-card"><div className="analytics-card-title"><div><strong>Źródła ruchu</strong><span>Skąd przychodzą odbiorcy</span></div><Activity/></div><div className="analytics-sources">{(data?.sources||[]).length?(data.sources as any[]).map((item,index)=><div key={item.source}><span>{index+1}</span><strong>{item.source==='direct'?'Wejścia bezpośrednie':item.source}</strong><b>{n(item.value)}</b></div>):<Empty text="Źródła pojawią się po pierwszych wizytach."/>}</div></article>
      </section>
    </>):<section className="analytics-customers">
      <div className="analytics-customer-tools"><div><strong>Baza kont Akademii</strong><span>{n((customers.data||[]).length)} wszystkich klientów</span></div><div className="analytics-customer-actions"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Szukaj po imieniu lub e-mailu"/></label><select value={customerFilter} onChange={e=>setCustomerFilter(e.target.value)} aria-label="Filtr klientów"><option value="ALL">Wszyscy</option><option value="BUYERS">Kupujący</option><option value="LEADS">Leady bez zakupu</option><option value="EMPTY">Bez aktywności</option></select><button onClick={()=>exportCustomers(filtered)}><Download/>CSV</button></div></div>
      {customers.isLoading?<Loading/>:<div className="analytics-customer-list">{filtered.length?filtered.map((customer:any)=><Customer key={customer.id} customer={customer} allCourses={courses.data||[]} pending={access.isPending} onAccess={(action,courseId)=>access.mutate({action,userId:customer.id,courseId})}/>):<Empty text="Nie znaleziono klientów."/>}</div>}
    </section>}
  </div>;
}

function Kpi({icon,label,value,note,trend}:{icon:React.ReactNode;label:string;value:string;note:string;trend?:number}){return <article className="analytics-kpi"><div className="analytics-kpi-icon">{icon}</div><span>{label}</span><strong>{value}</strong><div><small>{note}</small>{trend!==undefined&&trend!==0&&<em className={trend>0?'up':'down'}>{trend>0?<ArrowUpRight/>:<ArrowDownRight/>}{pct(Math.abs(trend))}</em>}</div></article>}
function TrafficChart({rows}:{rows:any[]}){const visible=rows.slice(-30);const max=Math.max(...visible.map(r=>r.visitors),1);return <div className="traffic-chart"><div className="traffic-bars">{visible.map((row,index)=><div key={row.date} title={`${date(row.date)}: ${row.visitors} użytkowników`}><i style={{height:`${Math.max(row.visitors/max*100,row.visitors?5:0)}%`}}/><span>{index===0||index===visible.length-1||index%7===0?new Date(row.date).getDate():''}</span></div>)}</div><div className="traffic-legend"><span><i/>Odwiedzający</span><b>Łącznie: {n(visible.reduce((sum,row)=>sum+row.visitors,0))} wizyt dziennych</b></div></div>}
function Customer({customer,allCourses,pending,onAccess}:{customer:any;allCourses:any[];pending:boolean;onAccess:(action:'grant'|'revoke',courseId:string)=>void}){const [open,setOpen]=useState(false);const [courseId,setCourseId]=useState('');const available=allCourses.filter(course=>!customer.courses.some((owned:any)=>owned.id===course.id));return <article className={`analytics-customer ${open?'open':''}`}><button onClick={()=>setOpen(!open)}><span className="analytics-customer-avatar">{customer.name?.[0]?.toUpperCase()||'K'}</span><span><strong>{customer.name}</strong><small>{customer.email}</small></span><span><strong>{customer.courses.length}</strong><small>kupione kursy</small></span><span><strong>{customer.interestedCourses.length}</strong><small>bez zakupu</small></span><span><strong>{date(customer.createdAt)}</strong><small>data konta</small></span><i>{open?'−':'+'}</i></button>{open&&<div className="analytics-customer-detail"><section><h3>Dostęp do kursów</h3>{customer.courses.length?customer.courses.map((course:any)=><div key={course.id}><span><strong>{course.title}</strong><small>Nadano {date(course.purchasedAt)} · postęp {Math.round(course.progress)}%</small></span><button className="analytics-revoke" disabled={pending} onClick={()=>onAccess('revoke',course.id)} title="Cofnij dostęp"><X/></button></div>):<p>Brak zakupionych kursów.</p>}<div className="analytics-grant"><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Wybierz kurs…</option>{available.map((course:any)=><option key={course.id} value={course.id}>{course.title}</option>)}</select><button disabled={!courseId||pending} onClick={()=>{onAccess('grant',courseId);setCourseId('');}}>Nadaj dostęp</button></div></section><section><h3>Zainteresowanie bez zakupu</h3>{customer.interestedCourses.length?customer.interestedCourses.map((course:any)=><div key={course.id}><span><strong>{course.title}</strong><small>Ostatnia wizyta {date(course.lastViewedAt)}</small></span>{course.checkoutStarted&&<b className="intent">Kliknął „Kup”</b>}</div>):<p>Brak zarejestrowanych wizyt na kartach kursów.</p>}</section></div>}</article>}
function Loading(){return <div className="analytics-loading">{[1,2,3,4].map(i=><i key={i}/>)}</div>}
function Empty({text}:{text:string}){return <div className="analytics-empty"><BarChart3/><p>{text}</p></div>}

function exportCustomers(customers:any[]){const rows=[['Imię i nazwisko','Email','Data konta','Kupione kursy','Zainteresowanie bez zakupu'],...customers.map(customer=>[customer.name,customer.email,date(customer.createdAt),customer.courses.map((c:any)=>c.title).join(' | '),customer.interestedCourses.map((c:any)=>c.title).join(' | ')])];const csv='\ufeff'+rows.map(row=>row.map(value=>`"${String(value).replace(/"/g,'""')}"`).join(';')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`klienci-akademii-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);}
