import { FormEvent, useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { academyApi } from '@/api/academy.api';

export function AcademyLegalAdmin() {
  const client = useQueryClient(); const { data, isLoading } = useQuery({ queryKey: ['academy', 'admin', 'legal'], queryFn: academyApi.adminGetLegal });
  const [seller, setSeller] = useState<Record<string, any>>({}); const [selectedId, setSelectedId] = useState(''); const [document, setDocument] = useState<Record<string, any>>({});
  useEffect(() => { if (data?.seller) setSeller(data.seller); if (data?.documents?.length && !selectedId) setSelectedId(data.documents[0].id); }, [data, selectedId]);
  useEffect(() => { const current = data?.documents?.find((item:any) => item.id === selectedId); if (current) setDocument(current); }, [data, selectedId]);
  const refresh = () => client.invalidateQueries({ queryKey: ['academy', 'admin', 'legal'] });
  const saveSeller = useMutation({ mutationFn: () => academyApi.adminUpdateSeller(seller), onSuccess: () => { toast.success('Dane sprzedawcy zapisane'); refresh(); }, onError: (error:any) => toast.error(error?.response?.data?.message || 'Nie udało się zapisać') });
  const saveDocument = useMutation({ mutationFn: () => academyApi.adminUpdateLegalDocument(document.id, { title: document.title, content: document.content, version: document.version, publish: true }), onSuccess: () => { toast.success('Dokument opublikowany'); refresh(); }, onError: (error:any) => toast.error(error?.response?.data?.message || 'Nie udało się opublikować') });
  if (isLoading) return <p>Ładowanie danych prawnych…</p>;
  const sellerFields = [['legalName','Pełna nazwa prawna'],['displayName','Nazwa wyświetlana'],['taxId','NIP — wymagany przed sprzedażą'],['registryNumber','REGON / numer rejestrowy'],['street','Ulica i numer'],['postalCode','Kod pocztowy'],['city','Miejscowość'],['country','Kraj'],['email','E-mail'],['phone','Telefon']];
  return <div className="academy-admin-form-page"><header><p className="academy-kicker">Zgodność sprzedaży</p><h1>Sprzedawca i dokumenty prawne</h1><p>Płatne zamówienia pozostają zablokowane, dopóki NIP i pozostałe dane nie są kompletne.</p></header><section><h2>Dane sprzedawcy</h2><form onSubmit={(e:FormEvent) => { e.preventDefault(); saveSeller.mutate(); }} className="academy-admin-field-grid">{sellerFields.map(([name,label]) => <label key={name}><span>{label}</span><input value={seller[name] || ''} onChange={e => setSeller(current => ({ ...current, [name]: e.target.value }))} required={!['registryNumber'].includes(name)} /></label>)}<button disabled={saveSeller.isPending}>Zapisz dane sprzedawcy</button></form></section><section><h2>Dokumenty</h2><div className="academy-document-editor"><nav>{data?.documents.map((item:any) => <button key={item.id} className={selectedId === item.id ? 'active' : ''} onClick={() => setSelectedId(item.id)}>{item.type}<small>{item.version} · {item.isPublished ? 'opublikowany' : 'szkic'}</small></button>)}</nav>{document.id && <form onSubmit={(e:FormEvent) => { e.preventDefault(); saveDocument.mutate(); }}><label><span>Tytuł</span><input value={document.title || ''} onChange={e => setDocument(current => ({ ...current, title: e.target.value }))} /></label><label><span>Wersja</span><input value={document.version || ''} onChange={e => setDocument(current => ({ ...current, version: e.target.value }))} /></label><label><span>Treść</span><textarea rows={24} value={document.content || ''} onChange={e => setDocument(current => ({ ...current, content: e.target.value }))} /></label><button disabled={saveDocument.isPending}>Zapisz i opublikuj</button></form>}</div></section></div>;
}
