import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { academyApi } from '@/api/academy.api';
import { toast } from 'sonner';

const bannerEmpty:any={title:'',subtitle:'',badge:'Nowość',imageUrl:'',mobileImageUrl:'',buttonLabel:'Zobacz ofertę',buttonUrl:'/#kursy',startsAt:'',endsAt:'',sortOrder:0,isActive:true};
const promotionEmpty:any={name:'',publicLabel:'Promocja',target:'ALL',targetIds:[],eligibleEmailsText:'',discountType:'PERCENTAGE',discountValue:10,startsAt:'',endsAt:'',isActive:true,newCustomersOnly:false,maxUses:'',maxUsesPerCustomer:1,minimumAmount:'',showCountdown:true};
const codeEmpty:any={...promotionEmpty,code:'',description:'',startsAt:'',endsAt:'',showCountdown:undefined};
const inputDate=(value?:string)=>value?new Date(value).toISOString().slice(0,16):'';

export function AcademyMarketingAdmin(){
  const client=useQueryClient(); const [tab,setTab]=useState<'banners'|'promotions'|'codes'|'leads'>('banners'); const [editing,setEditing]=useState('');
  const [form,setForm]=useState<any>(bannerEmpty);
  const [campaign,setCampaign]=useState({name:'',subject:'',content:'',audience:'NEWSLETTER',courseId:'',scheduledAt:''});
  const marketing=useQuery({queryKey:['academy','admin','marketing'],queryFn:academyApi.adminGetMarketing});
  const courses=useQuery({queryKey:['academy','admin','courses'],queryFn:academyApi.adminGetCourses});
  const bundles=useQuery({queryKey:['academy','admin','bundles'],queryFn:academyApi.adminGetBundles});
  const campaigns=useQuery({queryKey:['academy','admin','campaigns'],queryFn:academyApi.adminGetCampaigns});
  const reset=(next=tab)=>{setEditing('');setForm(next==='banners'?bannerEmpty:next==='promotions'?promotionEmpty:codeEmpty);};
  const change=(next:any)=>setForm((old:any)=>({...old,...next}));
  const save=useMutation({mutationFn:()=>editing?academyApi.adminUpdateMarketing(tab,editing,form):academyApi.adminCreateMarketing(tab,form),onSuccess:()=>{toast.success('Zapisano');reset();client.invalidateQueries({queryKey:['academy','admin','marketing']});},onError:(e:any)=>toast.error(e?.response?.data?.message||'Nie udało się zapisać')});
  const remove=useMutation({mutationFn:(id:string)=>academyApi.adminDeleteMarketing(tab,id),onSuccess:()=>client.invalidateQueries({queryKey:['academy','admin','marketing']})});
  const sendCampaign=useMutation({mutationFn:()=>academyApi.adminSendMarketingCampaign(campaign),onSuccess:(result:any)=>{toast.success(`Kampania zapisana dla ${result.recipients} odbiorców`);setCampaign({...campaign,name:'',subject:'',content:'',scheduledAt:''});client.invalidateQueries({queryKey:['academy','admin','campaigns']});},onError:(e:any)=>toast.error(e?.response?.data?.message||'Nie udało się zapisać kampanii')});
  const testCampaign=useMutation({mutationFn:()=>academyApi.adminTestCampaign(campaign),onSuccess:()=>toast.success('Wiadomość testowa wysłana na konto administratora')});
  const selectTab=(value:any)=>{setTab(value);setEditing('');setForm(value==='banners'?bannerEmpty:value==='promotions'?promotionEmpty:codeEmpty);};
  const edit=(row:any)=>{setEditing(row.id);setForm({...row,eligibleEmailsText:(row.eligibleEmails||[]).join('\n'),startsAt:inputDate(row.startsAt),endsAt:inputDate(row.endsAt),maxUses:row.maxUses??'',minimumAmount:row.minimumAmount??''});};
  const rows=(marketing.data?.[tab]||[]) as any[];
  const targets=form.target==='COURSE'?(courses.data||[]):form.target==='BUNDLE'?(bundles.data||[]):[];
  const toggleTarget=(id:string)=>change({targetIds:form.targetIds?.includes(id)?form.targetIds.filter((x:string)=>x!==id):[...(form.targetIds||[]),id]});
  return <div className="academy-admin-form-page"><header><p className="academy-kicker">Marketing Akademii</p><h1>Banery, promocje i leady</h1><p>Zaplanuj komunikację, automatyczne rabaty i pozyskiwanie klientów.</p></header>
    <nav className="analytics-tabs">{[['banners','Banery'],['promotions','Promocje'],['codes','Kody rabatowe'],['leads','Leady']].map(([key,label])=><button className={tab===key?'active':''} onClick={()=>selectTab(key)} key={key}>{label}</button>)}</nav>
    {tab==='leads'&&<LeadCrm rows={rows}/>}
    {tab!=='leads'&&<MarketingPreview tab={tab} form={form}/>}
    {tab==='leads'?<><section><h2>Zaplanuj kampanię lub premierę</h2><form className="academy-admin-field-grid" onSubmit={e=>{e.preventDefault();sendCampaign.mutate();}}><Field label="Nazwa wewnętrzna"><input value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/></Field><Field label="Odbiorcy"><select value={campaign.audience} onChange={e=>setCampaign({...campaign,audience:e.target.value})}><option value="NEWSLETTER">Newsletter</option><option value="LEAD_MAGNET">Osoby pobierające materiały</option><option value="WAITLIST">Lista oczekujących</option><option value="ALL">Wszyscy ze zgodą</option></select></Field>{campaign.audience==='WAITLIST'&&<Field label="Kurs"><select required value={campaign.courseId} onChange={e=>setCampaign({...campaign,courseId:e.target.value})}><option value="">Wybierz kurs</option>{(courses.data||[]).map((course:any)=><option key={course.id} value={course.id}>{course.title}</option>)}</select></Field>}<Field label="Termin wysyłki"><input type="datetime-local" value={campaign.scheduledAt} onChange={e=>setCampaign({...campaign,scheduledAt:e.target.value})}/></Field><Field label="Temat" wide><input required value={campaign.subject} onChange={e=>setCampaign({...campaign,subject:e.target.value})}/></Field><Field label="Treść wiadomości" wide><textarea required minLength={10} value={campaign.content} onChange={e=>setCampaign({...campaign,content:e.target.value})}/></Field><div className="wide academy-email-preview"><strong>Podgląd wiadomości</strong><h3>{campaign.subject||'Temat wiadomości'}</h3><p>{campaign.content||'Tutaj pojawi się treść kampanii.'}</p></div><button type="button" onClick={()=>testCampaign.mutate()} disabled={!campaign.subject||!campaign.content}>Wyślij test</button><button disabled={sendCampaign.isPending}>{sendCampaign.isPending?'Zapisywanie…':'Zaplanuj kampanię'}</button></form></section><section><h2>Historia kampanii</h2><div className="academy-admin-card-list">{(campaigns.data||[]).map((row:any)=><article key={row.id}><div><strong>{row.name}</strong><p>{row.status} · {row.sentCount}/{row.recipients} wysłanych · {row.openedCount} otwarć · {row.clickedCount} kliknięć · {row.failedCount} błędów</p></div></article>)}</div></section><section><h2>Newsletter, materiały i listy oczekujących</h2><button onClick={()=>exportLeads(rows)}>Eksportuj CSV</button><div className="academy-admin-card-list">{rows.map(row=><article key={row.id}><div><strong>{row.email}</strong><p>{row.type} · {row.courseId||'ogólny zapis'} · {row.unsubscribedAt?'wypisany':'aktywny'} · {row.isCustomer?'klient':'lead'} · {(row.tags||[]).join(', ')} · {new Date(row.createdAt).toLocaleDateString('pl-PL')}</p></div></article>)}</div></section></>:<>
      <section><h2>{editing?'Edytuj':'Dodaj'} {tab==='banners'?'baner':tab==='promotions'?'promocję':'kod'}</h2><form className="academy-admin-field-grid" onSubmit={(e:FormEvent)=>{e.preventDefault();save.mutate();}}>
        {tab==='banners'?<><Field label="Tytuł"><input required value={form.title} onChange={e=>change({title:e.target.value})}/></Field><Field label="Etykieta"><input value={form.badge} onChange={e=>change({badge:e.target.value})}/></Field><Field label="Treść" wide><textarea value={form.subtitle} onChange={e=>change({subtitle:e.target.value})}/></Field><Field label="Obraz desktop"><input value={form.imageUrl} onChange={e=>change({imageUrl:e.target.value})}/></Field><Field label="Obraz mobile"><input value={form.mobileImageUrl} onChange={e=>change({mobileImageUrl:e.target.value})}/></Field><Field label="Tekst przycisku"><input value={form.buttonLabel} onChange={e=>change({buttonLabel:e.target.value})}/></Field><Field label="Link przycisku"><input value={form.buttonUrl} onChange={e=>change({buttonUrl:e.target.value})}/></Field><Field label="Kolejność"><input type="number" value={form.sortOrder} onChange={e=>change({sortOrder:Number(e.target.value)})}/></Field></>:<><Field label={tab==='codes'?'Kod':'Nazwa'}><input required value={tab==='codes'?form.code:form.name} onChange={e=>change(tab==='codes'?{code:e.target.value.toUpperCase()}:{name:e.target.value})}/></Field><Field label={tab==='codes'?'Opis wewnętrzny':'Etykieta dla klienta'}><input value={tab==='codes'?form.description:form.publicLabel} onChange={e=>change(tab==='codes'?{description:e.target.value}:{publicLabel:e.target.value})}/></Field><Field label="Typ rabatu"><select value={form.discountType} onChange={e=>change({discountType:e.target.value})}><option value="PERCENTAGE">Procentowy</option><option value="AMOUNT">Kwotowy</option></select></Field><Field label="Wartość"><input required min="0.01" step="0.01" type="number" value={form.discountValue} onChange={e=>change({discountValue:Number(e.target.value)})}/></Field><Field label="Obejmuje"><select value={form.target} onChange={e=>change({target:e.target.value,targetIds:[]})}><option value="ALL">Wszystkie produkty</option><option value="COURSE">Wybrane kursy</option><option value="BUNDLE">Wybrane pakiety</option></select></Field><Field label="Minimalny zakup"><input type="number" value={form.minimumAmount} onChange={e=>change({minimumAmount:e.target.value})}/></Field><Field label="Limit wszystkich użyć"><input type="number" value={form.maxUses} onChange={e=>change({maxUses:e.target.value})}/></Field><Field label="Limit na klienta"><input type="number" min="1" value={form.maxUsesPerCustomer} onChange={e=>change({maxUsesPerCustomer:Number(e.target.value)})}/></Field></>}
        <Field label="Start"><input required={tab==='promotions'} type="datetime-local" value={form.startsAt} onChange={e=>change({startsAt:e.target.value})}/></Field><Field label="Koniec"><input required={tab==='promotions'} type="datetime-local" value={form.endsAt} onChange={e=>change({endsAt:e.target.value})}/></Field>
        {targets.length>0&&<fieldset className="wide"><legend>Produkty objęte akcją (brak zaznaczeń = wszystkie)</legend>{targets.map((item:any)=><label className="academy-check" key={item.id}><input type="checkbox" checked={form.targetIds?.includes(item.id)} onChange={()=>toggleTarget(item.id)}/><span>{item.title}</span></label>)}</fieldset>}
        {tab!=='banners'&&<Field label="Tylko wskazane adresy e-mail (opcjonalnie, po jednym w linii)" wide><textarea value={form.eligibleEmailsText||''} onChange={e=>change({eligibleEmailsText:e.target.value})}/></Field>}
        <label className="academy-check"><input type="checkbox" checked={form.isActive} onChange={e=>change({isActive:e.target.checked})}/><span>Aktywne</span></label>{tab!=='banners'&&<label className="academy-check"><input type="checkbox" checked={form.newCustomersOnly} onChange={e=>change({newCustomersOnly:e.target.checked})}/><span>Tylko nowi klienci</span></label>}{tab==='promotions'&&<label className="academy-check"><input type="checkbox" checked={form.showCountdown} onChange={e=>change({showCountdown:e.target.checked})}/><span>Odliczanie czasu</span></label>}
        <button disabled={save.isPending}>Zapisz</button>{editing&&<button type="button" onClick={()=>reset()}>Anuluj</button>}
      </form></section>
      <section><h2>Istniejące i wyniki</h2><div className="academy-admin-card-list">{rows.map(row=><article key={row.id}><div><strong>{row.title||row.name||row.code}</strong><p>{row.isActive?'Aktywne':'Wyłączone'} · {tab==='banners'?`${row.clicks} kliknięć / ${row.impressions} wyświetleń · CTR ${row.impressions?((row.clicks/row.impressions)*100).toFixed(1):'0,0'}%`:`${row.paidOrders||0} opłaconych zamówień · ${Number(row.revenue||0).toLocaleString('pl-PL')} zł przychodu · ${Number(row.totalDiscount||0).toLocaleString('pl-PL')} zł rabatu`}</p></div><button onClick={()=>edit(row)}>Edytuj</button><button onClick={()=>remove.mutate(row.id)}>Usuń</button></article>)}</div></section></>}
  </div>;
}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?'wide':''}><span>{label}</span>{children}</label>}
function exportLeads(rows:any[]){const csv='\ufeff'+[['Email','Imię','Typ','Kurs','Źródło','Data'],...rows.map(r=>[r.email,r.name||'',r.type,r.courseId||'',r.source||'',r.createdAt])].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='leady-akademii.csv';a.click();URL.revokeObjectURL(url);}
function LeadCrm({rows}:{rows:any[]}){const client=useQueryClient();const [search,setSearch]=useState('');const [type,setType]=useState('ALL');const [segment,setSegment]=useState('ALL');const update=useMutation({mutationFn:({id,data}:{id:string;data:any})=>academyApi.adminUpdateLead(id,data),onSuccess:()=>client.invalidateQueries({queryKey:['academy','admin','marketing']})});const remove=useMutation({mutationFn:academyApi.adminDeleteLead,onSuccess:()=>client.invalidateQueries({queryKey:['academy','admin','marketing']})});const filtered=rows.filter(row=>`${row.email} ${row.name||''} ${(row.tags||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase())).filter(row=>type==='ALL'||row.type===type).filter(row=>segment==='CUSTOMER'?row.isCustomer:segment==='LEAD'?!row.isCustomer:true);return <section><h2>CRM leadów</h2><div className="analytics-customer-actions"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Szukaj e-maila, imienia lub tagu"/><select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">Wszystkie źródła</option><option value="NEWSLETTER">Newsletter</option><option value="LEAD_MAGNET">Materiały</option><option value="WAITLIST">Lista oczekujących</option><option value="ABANDONED_CHECKOUT">Porzucone zakupy</option></select><select value={segment} onChange={e=>setSegment(e.target.value)}><option value="ALL">Leady i klienci</option><option value="LEAD">Tylko leady</option><option value="CUSTOMER">Tylko klienci</option></select><button onClick={()=>exportLeads(filtered)}>Eksport segmentu</button></div><div className="academy-admin-card-list">{filtered.map(row=><article key={row.id}><div><strong>{row.email}</strong><p>{row.type} · {row.utmSource||row.source||'direct'} / {row.utmMedium||'-'} / {row.utmCampaign||'-'} · {row.isCustomer?'klient':'lead'} · {(row.tags||[]).join(', ')}</p></div><button onClick={()=>{const value=window.prompt('Tagi po przecinku',(row.tags||[]).join(', '));if(value!==null)update.mutate({id:row.id,data:{tags:value.split(',').map((v:string)=>v.trim()).filter(Boolean)}})}}>Tagi</button><button onClick={()=>update.mutate({id:row.id,data:{unsubscribed:!row.unsubscribedAt}})}>{row.unsubscribedAt?'Przywróć':'Wypisz'}</button><button onClick={()=>{if(window.confirm('Usunąć dane tego leada?'))remove.mutate(row.id)}}>Usuń dane</button></article>)}</div></section>}
function MarketingPreview({tab,form}:{tab:string;form:any}){return <section><h2>Podgląd przed publikacją</h2>{tab==='banners'?<div className="academy-marketing-slider" style={form.imageUrl?{backgroundImage:`linear-gradient(90deg,#173c2dcc,#173c2d55),url(${form.imageUrl})`}:undefined}><div><span>{form.badge}</span><h2>{form.title||'Tytuł banera'}</h2><p>{form.subtitle||'Treść banera pojawi się tutaj.'}</p><a>{form.buttonLabel||'Przycisk'}</a></div></div>:<article className="academy-course-card"><div className="academy-course-body"><span className="academy-kicker">{tab==='codes'?'Kod rabatowy':'Promocja'}</span><h3>{form.name||form.code||'Nazwa akcji'}</h3><p>{form.publicLabel||form.description||'Opis dla klienta'}</p><strong>{form.discountValue||0}{form.discountType==='PERCENTAGE'?'%':' zł'} rabatu</strong>{form.endsAt&&<small>Aktywna do {new Date(form.endsAt).toLocaleString('pl-PL')}</small>}</div></article>}</section>}
