import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { academyApi } from '@/api/academy.api';

const empty = { title:'',slug:'',description:'',price:'',compareAtPrice:'',accessDays:'',isActive:true,isFeatured:false,thumbnailUrl:'',courseIds:[] as string[] };
export function AcademyBundlesAdmin(){
  const client=useQueryClient(); const {data:bundles=[]}=useQuery({queryKey:['academy','admin','bundles'],queryFn:academyApi.adminGetBundles}); const {data:courses=[]}=useQuery({queryKey:['academy','admin','courses'],queryFn:academyApi.adminGetCourses}); const [form,setForm]=useState<any>(empty); const [editing,setEditing]=useState('');
  const save=useMutation({mutationFn:()=>{const input={...form,price:Number(form.price),compareAtPrice:form.compareAtPrice?Number(form.compareAtPrice):null,accessDays:form.accessDays?Number(form.accessDays):null};return editing?academyApi.adminUpdateBundle(editing,input):academyApi.adminCreateBundle(input);},onSuccess:()=>{toast.success('Pakiet zapisany');setForm(empty);setEditing('');client.invalidateQueries({queryKey:['academy','admin','bundles']});},onError:(error:any)=>toast.error(error?.response?.data?.message||'Nie udało się zapisać')});
  const edit=(bundle:any)=>{setEditing(bundle.id);setForm({...bundle,price:String(bundle.price),compareAtPrice:bundle.compareAtPrice?String(bundle.compareAtPrice):'',accessDays:bundle.accessDays?String(bundle.accessDays):'',courseIds:bundle.courses.map((item:any)=>item.courseId)});};
  const toggle=(courseId:string)=>setForm((current:any)=>({...current,courseIds:current.courseIds.includes(courseId)?current.courseIds.filter((id:string)=>id!==courseId):[...current.courseIds,courseId]}));
  return <div className="academy-admin-form-page"><header><p className="academy-kicker">Oferta łączona</p><h1>Pakiety kursów</h1><p>Pakiet jest jednym produktem sprzedażowym i po opłaceniu nadaje dostęp do wszystkich wskazanych kursów.</p></header><section><h2>{editing?'Edytuj pakiet':'Nowy pakiet'}</h2><form onSubmit={(e:FormEvent)=>{e.preventDefault();save.mutate();}} className="academy-admin-field-grid"><label><span>Nazwa</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>Slug</span><input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label><span>Cena brutto PLN</span><input required type="number" min="0.01" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label><span>Cena przed obniżką</span><input type="number" step="0.01" value={form.compareAtPrice} onChange={e=>setForm({...form,compareAtPrice:e.target.value})}/></label><label><span>Dni dostępu (puste = bezterminowo)</span><input type="number" min="1" value={form.accessDays} onChange={e=>setForm({...form,accessDays:e.target.value})}/></label><label className="wide"><span>Opis</span><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><fieldset className="wide"><legend>Kursy w pakiecie — wybierz min. 2</legend>{(courses as any[]).map(course=><label className="academy-check" key={course.id}><input type="checkbox" checked={form.courseIds.includes(course.id)} onChange={()=>toggle(course.id)}/><span>{course.title} · {Number(course.price).toFixed(2)} zł</span></label>)}</fieldset><label className="academy-check"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/><span>Aktywny w sprzedaży</span></label><label className="academy-check"><input type="checkbox" checked={form.isFeatured} onChange={e=>setForm({...form,isFeatured:e.target.checked})}/><span>Wyróżniony</span></label><button disabled={save.isPending||form.courseIds.length<2}>{editing?'Zapisz zmiany':'Utwórz pakiet'}</button>{editing&&<button type="button" onClick={()=>{setEditing('');setForm(empty);}}>Anuluj edycję</button>}</form></section><section><h2>Istniejące pakiety</h2><div className="academy-admin-card-list">{(bundles as any[]).map(bundle=><article key={bundle.id}><div><strong>{bundle.title}</strong><p>{bundle.courses.length} kursy · {Number(bundle.price).toFixed(2)} zł · {bundle.isActive?'aktywny':'wyłączony'}</p></div><button onClick={()=>edit(bundle)}>Edytuj</button></article>)}</div></section></div>;
}
