import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { academyApi } from '@/api/academy.api';

const empty={title:'',slug:'',description:'',price:'',compareAtPrice:'',accessDays:'',displayOrder:0,isActive:true,isFeatured:false,thumbnailUrl:'',courseIds:[] as string[]};
export function AcademyBundlesAdmin(){
  const client=useQueryClient();const {data:bundles=[]}=useQuery({queryKey:['academy','admin','bundles'],queryFn:academyApi.adminGetBundles});const {data:courses=[]}=useQuery({queryKey:['academy','admin','courses'],queryFn:academyApi.adminGetCourses});const [form,setForm]=useState<any>(empty);const [editing,setEditing]=useState('');
  const save=useMutation({mutationFn:()=>{const input={...form,price:Number(form.price),compareAtPrice:form.compareAtPrice?Number(form.compareAtPrice):null,accessDays:form.accessDays?Number(form.accessDays):null,displayOrder:Number(form.displayOrder)||0};return editing?academyApi.adminUpdateBundle(editing,input):academyApi.adminCreateBundle(input);},onSuccess:()=>{toast.success('Pakiet zapisany');setForm(empty);setEditing('');client.invalidateQueries({queryKey:['academy','admin','bundles']});},onError:(error:any)=>toast.error(error?.response?.data?.message||'Nie udało się zapisać')});
  const edit=(bundle:any)=>{setEditing(bundle.id);setForm({...bundle,price:String(bundle.price),compareAtPrice:bundle.compareAtPrice?String(bundle.compareAtPrice):'',accessDays:bundle.accessDays?String(bundle.accessDays):'',displayOrder:bundle.displayOrder||0,courseIds:bundle.courses.map((item:any)=>item.courseId)});};
  const set=(name:string,value:any)=>setForm((current:any)=>({...current,[name]:value}));
  const toggle=(id:string)=>set('courseIds',form.courseIds.includes(id)?form.courseIds.filter((value:string)=>value!==id):[...form.courseIds,id]);
  return <div className="academy-admin-form-page"><header><p className="academy-kicker">Oferta łączona</p><h1>Pakiety kursów</h1><p>Twórz produkty łączone, ustalaj ich cenę, kolejność i widoczność.</p></header><section><h2>{editing?'Edytuj pakiet':'Nowy pakiet'}</h2><form onSubmit={(e:FormEvent)=>{e.preventDefault();save.mutate();}} className="academy-admin-field-grid"><Field label="Nazwa"><input required value={form.title} onChange={e=>set('title',e.target.value)}/></Field><Field label="Slug"><input required value={form.slug} onChange={e=>set('slug',e.target.value)}/></Field><Field label="Cena brutto PLN"><input required type="number" min="0.01" step="0.01" value={form.price} onChange={e=>set('price',e.target.value)}/></Field><Field label="Cena przed obniżką"><input type="number" step="0.01" value={form.compareAtPrice} onChange={e=>set('compareAtPrice',e.target.value)}/></Field><Field label="Dni dostępu"><input type="number" min="1" value={form.accessDays} onChange={e=>set('accessDays',e.target.value)}/></Field><Field label="Kolejność w sklepie"><input type="number" min="0" value={form.displayOrder} onChange={e=>set('displayOrder',e.target.value)}/></Field><Field label="Adres okładki"><input value={form.thumbnailUrl} onChange={e=>set('thumbnailUrl',e.target.value)}/></Field><Field label="Opis" wide><textarea required value={form.description} onChange={e=>set('description',e.target.value)}/></Field><fieldset className="wide"><legend>Kursy w pakiecie — wybierz minimum 2</legend>{(courses as any[]).map(course=><label className="academy-check" key={course.id}><input type="checkbox" checked={form.courseIds.includes(course.id)} onChange={()=>toggle(course.id)}/><span>{course.title} · {Number(course.price).toFixed(2)} zł</span></label>)}</fieldset><label className="academy-check"><input type="checkbox" checked={form.isActive} onChange={e=>set('isActive',e.target.checked)}/><span>Aktywny w sprzedaży</span></label><label className="academy-check"><input type="checkbox" checked={form.isFeatured} onChange={e=>set('isFeatured',e.target.checked)}/><span>Wyróżniony pakiet</span></label><button disabled={save.isPending||form.courseIds.length<2}>{editing?'Zapisz zmiany':'Utwórz pakiet'}</button>{editing&&<button type="button" onClick={()=>{setEditing('');setForm(empty);}}>Anuluj</button>}</form></section><section><h2>Istniejące pakiety</h2><div className="academy-admin-card-list">{(bundles as any[]).map(bundle=><article key={bundle.id}><div><strong>{bundle.title}</strong><p>{bundle.courses.length} kursy · {Number(bundle.price).toFixed(2)} zł · pozycja {bundle.displayOrder||0} · {bundle.isActive?'aktywny':'wyłączony'}</p></div><button onClick={()=>edit(bundle)}>Edytuj</button></article>)}</div></section></div>;
}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?'wide':''}><span>{label}</span>{children}</label>}
