export const SEO = {
  siteName: 'BeskidStudio By Wiktoria Ćwik',
  domain: 'https://kosmetologwiktoriacwik.pl',
  phone: '+48532128227',
  email: 'kontakt@kosmetologwiktoriacwik.pl',
  address: {
    street: 'Mordarka 505',
    city: 'Mordarka',
    postalCode: '34-600',
    region: 'Małopolskie',
  },
  lat: 49.689496,
  lon: 20.455024,
  fbProfile: 'https://www.facebook.com/kosmetologwiktoriacwik/',
  igProfile: 'https://www.instagram.com/kosmetolog__wiktoria_cwik/',
  ttProfile: 'https://www.tiktok.com/@wiktoriabeauty_brows',
  mapQuery: 'Mordarka 505, 34-600 Mordarka, Polska',
  googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Mordarka%20505%2C%2034-600%20Mordarka%2C%20Polska',
  googleBusinessUrl: 'https://www.google.com/maps/search/?api=1&query=BeskidStudio+By+Wiktoria+%C4%86wik+Mordarka+505',
  googleReviewUrl: 'https://www.google.com/maps/search/?api=1&query=BeskidStudio+By+Wiktoria+%C4%86wik+Mordarka+505',
  owner: {
    name: 'Wiktoria Ćwik',
    role: 'Dyplomowany kosmetolog',
  },
  openingHours: [
    { days: 'Poniedziałek – Piątek', hours: '09:00 – 18:00' },
    { days: 'Sobota',                hours: '09:00 – 14:00' },
    { days: 'Niedziela',             hours: 'Nieczynne' },
  ],
};
